### ISSUE TITLE
[BUG]  Input lag up to 2 seconds.

### ISSUE THREAD

**Issue by nicktelindert** [hmlendea/gfn-electron#162]
### Describe the bug

I suffer from a lot of input lag and slow downs when using this App on Arch Linux. 
I do have the intel-media-driver installed and it seems to work fine according to vainfo.

I use a wired connection and i have a 100 Mbit fiber connection.

### To Reproduce

1. Launch any game on an Arch Linux system (I used Blair Witch and Worms Reloaded)
2. The first minute the game reacts acceptable.
3. After the first few minutes i get a latency of pretty much 2 seconds on my all my input(Mouse/Keyboard).
4. The mouse is wired, Keyboard is connected by bluetooth

It testing Geforce Now on Chrome OS flex on the same system and the performance difference is huge, it is pretty much a native gaming experience.

In the past i have used this Geforce Now app on Ubuntu(Snap version), i don't think i had these lag issues on Ubuntu at all. 

I am pretty sure its Arch Linux related, i tried to set the driver to iHD manually to make sure it does find the VAAPI driver and when launching from the terminal it does show VAAPI related output.

### Operating System

Arch Linux

### Desktop Environment

Gnome 42

### Display Server

Wayland

### Installation method

App Image

### Version

1.8.0

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Right away

### Additional context

CPU:  i5-8250U
Onboard GPU: Intel UHD 620
Ram: 8GB
Storage: 256 m2 SSD

**Comment by hmlendea** [comment]
Is this issue still affecting the latest supported versions?

**Comment by RPwnage** [comment]
> Is this issue still affecting the latest supported versions?

yes

**Comment by CheesyChocolate** [comment]
I no longer have access to my old hardware and no longer is using geforce now. 
I remember, To workaround the issue I made a [fork](https://github.com/CheesyChocolate/gfn-electron) that would work on the old hardware.

**Comment by hditano** [comment]
> I no longer have access to my old hardware and no longer is using geforce now. I remember, To workaround the issue I made a [fork](https://github.com/CheesyChocolate/gfn-electron) that would work on the old hardware.

Omg!!

Thank you!!! I was finally able to play Geforce Now w/o any lag at all

FYI this are my specs:

```
CPU: quad core Intel Core i5-8350U (-MT MCP-) speed/min/max: 2000/400/3600 MHz
    Kernel: 6.10.5-arch1-1 x86_64 Up: 1d 4h 38m Mem: 10.87/31.22 GiB (34.8%)
    Storage: 2.29 TiB (45.1% used) Procs: 338 Shell: Zsh inxi: 3.3.35
Graphics:
  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel
    arch: Gen-9.5 process: Intel 14nm built: 2016-20 ports:
    active: HDMI-A-2,eDP-1 empty: DP-1,DP-2,HDMI-A-1 bus-ID: 00:02.0
    chip-ID: 8086:5917 class-ID: 0300
  Device-2: Chicony Integrated Camera (1280x720@30) driver: uvcvideo
    type: USB rev: 2.0 speed: 480 Mb/s lanes: 1 mode: 2.0 bus-ID: 1-8:4
    chip-ID: 04f2:b604 class-ID: 0e02 serial: 0001
  Display: x11 server: X.Org v: 21.1.13 driver: X: loaded: modesetting
    alternate: fbdev,intel,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x2160 s-dpi: 96 s-size: 506x570mm (19.92x22.44")
    s-diag: 762mm (30.01")
  Monitor-1: HDMI-A-2 mapped: HDMI-2 pos: top model: LG (GoldStar) ULTRAGEAR
    serial: 108MAJM2AN88 built: 2021 res: 1920x1080 hz: 120 dpi: 70 gamma: 1.2
    size: 697x392mm (27.44x15.43") diag: 800mm (31.5") ratio: 16:9 modes:
    max: 3840x2160 min: 640x480
  Monitor-2: eDP-1 pos: primary,bottom model: LG Display 0x0521 built: 2016
    res: 1920x1080 hz: 60 dpi: 158 gamma: 1.2 size: 309x174mm (12.17x6.85")
    diag: 355mm (14") ratio: 16:9 modes: 1920x1080
  API: EGL v: 1.5 hw: drv: intel iris platforms: device: 0 drv: iris
    device: 1 drv: swrast gbm: drv: iris surfaceless: drv: iris x11: drv: iris
    inactive: wayland
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 24.1.6-arch1.1
    glx-v: 1.4 direct-render: yes renderer: Mesa Intel UHD Graphics 620 (KBL
    GT2) device-ID: 8086:5917 memory: 15.25 GiB unified: yes
```
